import {
  ArrowLeft,
  ArrowRight,
  ArrowDown,
  ArrowUpRight,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Download,
  Eye,
  EyeOff,
  Globe,
  GripVertical,
  LogOut,
  Mail,
  Menu,
  Minus,
  Monitor,
  Pencil,
  Phone,
  Plus,
  Smartphone,
  Trash2,
  Upload,
  X,
  type LucideIcon,
} from 'lucide-react'

import type { IconName } from '@/constants/icons'

/** Zatvoren spisak — samo ove ikonice ulaze u bundle (constants/icons.ts). */
export const ICONS: Record<IconName, LucideIcon> = {
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUpRight: ArrowUpRight,
  arrowDown: ArrowDown,
  check: Check,
  close: X,
  menu: Menu,
  mail: Mail,
  plus: Plus,
  minus: Minus,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  calendar: Calendar,
  clock: Clock,
  globe: Globe,
  phone: Phone,
  monitor: Monitor,
  smartphone: Smartphone,
  logOut: LogOut,
  trash: Trash2,
  edit: Pencil,
  upload: Upload,
  download: Download,
  eye: Eye,
  eyeOff: EyeOff,
  grip: GripVertical,
}
